/*

Codewars, 7k: Coloured Triangle

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G
A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

*/

const triangle = r => {
  let str = '';
  let rgb = 'RGB';
  if (r.length === 1) return r;

  for (let i = 0; i < r.length - 1; i++) {
    if (r[i] === r[i+1]) {
      str += r[i];
    } else {
      str += rgb.replace(r[i], '').replace(r[i+1], '');
    }
  }
  if (str.length > 1) {
    return triangle(str);
  } else {
    return str;
  }
};

console.log(triangle('RBRGBRBGGRRRBGBBBGG'))